# on:
#   release:
#     types: [published]

# on:
#   push:
#     branches:
#       - stage

on:
  schedule:
    - cron: '*/3 * * * 1-5'
    # - cron: '0 */2 * * 1-5'

name: test workflow

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: set-env
    #   id: set-env
    #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    # - name: echo-env
    #   id: echo-env
    #   run: echo ${{ steps.set-env.outputs.VERSION }}

    - name: echo
      id: echo
      run: echo "hello world"
