on:
  release:
    types: [published]

name: release-test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: echo
      run: echo ${{GITHUB_REF}}
