# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - stage

# on:
#   schedule:
#     - cron: '*/5 * * * 1-5'

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

name: test workflow

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: set-env
    #   id: set-env
    #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    # - name: echo-env
    #   id: echo-env
    #   run: echo ${{ steps.set-env.outputs.VERSION }}

    - name: echo
      id: echo
      run: echo "hello world"

    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: success()
      env:
        SLACK_TITLE: E2E Test Failure
        SLACK_USERNAME: ci-bot
        SLACK_ICON_EMOJI: ':robot_face:'
        SLACK_COLOR: danger
        SLACK_MESSAGE: 'E2E Test Failed :warning:'
